name: notify person on duty

on: 
  workflow_dispatch:
  schedule:
    - cron: "5 23,9 * * *"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: trigger dingtalk webhook
      env:
        dingtalk_key: ${{ secrets.dingtalk_key }}
        holiday_key: ${{ secrets.holiday_key }}
        TZ: Asia/Shanghai
      run: |
        python notify.py "$dingtalk_key" "$holiday_key"
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "main"    
