# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyDes requests base64
    - name: trigger dingtalk webhook
      env:
        dingtalk_key: ${{ secrets.dingtalk_key }}
        holiday_key: ${{ secrets.holiday_key }}
        des_key: ${{ secrets.des_key }}
      run: |
        python notify.py "$dingtalk_key" "$holiday_key" "$des_key"
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "main"    